.Dd September 28, 2023
.Dt XMSLOCKDIR 1
.Sh NAME
.Nm xmslockdir
.Nd mouse direction locker for X
.Sh SYNOPSIS
.Nm
.Op Fl hvxy
.Sh DESCRIPTION
The
.Nm
application lets you lock the direction of movement of the mouse.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.It Fl x
lock the mouse movement to only the x axis
.It Fl y
lock the mouse movement to only the y axis
.El
.Sh SEE ALSO
.Xr X 7
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xmslockdir/issues
