#!/bin/sh -e

if test "$1" != "-x" && test "$1" != "-y"; then
	echo "xmslockdir-toggle: invalid option" >/dev/stderr
	exit 1
fi

if test -e /tmp/xmslockdir.pid; then
	pid=$(cat /tmp/xmslockdir.pid)
	if ps -p "$pid" >/dev/null; then
		kill -2 "$pid"
	fi
	rm -f /tmp/xmslockdir.pid
else
	# shellcheck disable=SC2086
	xmslockdir $1 &
	echo $! > /tmp/xmslockdir.pid
fi
